title: Welcome to carverd
description: I'm a spatial scientist working in Colorado. This is my place for sharing turorials, projects, and other thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://carverd.com/ # the base hostname & protocol for your site, e.g. http://example.com


# Author
author-name:    Dan Carver
author-image:   headshot.jpg
author-job:     Spatial Scientist
author-email:   dan.carver@carverd.com # Add your email for contant form.
about-author:   I am a spatial scientist primarily writing in R.

# Social settings
social-twitter:
social-facebook:
social-github:    dcarver1
social-pinterest:
social-instagram:
social-youtube: channel/UClEdtZNnxtnEYllNFCXDl8Q
social-vk:
social-linkedin: daniel-carver-0439a7113

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
