---
output:
  pdf_document: default
  html_document: default
  title:  Daniel Carver
urlcolor: blue
---
# Dan Carver 
## US Citizen 
### carver.dan1@gmail.com | 630-621-6557
#### [carverd.com](http://www.carverd.com)

***

# Education

## University of Colorado Denver
**Masters of Applied Geography and Geospatial Science**

Graduation Date: May 2017 | GPA: 3.86

*Masters Certificate in Geographic Information Science*



## Adams State University
**B.S. Geology & B.A. Physical Geography**

Graduation Date: May 2012 | GPA: 3.7

***

# Work Experience

#### United States Department of Agriculture; Agricultural Research Service
*Spatial Scientist*

June 2018 to Present | Fort Collins, CO

> I collaborate with researchers and curators at the National Laboratory for Genetic Resource Preservation to develop geospatial models that add to the understanding of the distribution, collection, and use of Crop Wild Relatives.

 - Generate Geospatial models of potential plant locations
 - Produce reports on the relationship between the ARS and BLM's Seeds of Success Program
 - Contribute to the geospatial analysis needs of other USDA researchers

Supervisor: Colin Khoury  970-492-7534

Reason for Leaving: 180 day work contract

<br>

#### NASA DEVELOP
*Geoinformatics Fellow and Assistant Center Lead*

June 2017 to September 2018 | Fort Collins, CO

> Half of my time was spent supporting the node located in Fort Collins and the other half was spent supporting the National Program office in Virginia. At the node level I assisted in administrative tasks and worked as a member of a research team. At the national level I provided educational trainings and supported the 13 nodes across the country by troubleshooting geospatial processing questions.

- Collaborate with Center Lead to maintain day to day operations of 8-10 employees and 6 distinct research projects a year.
- Develop project proposals and maintain relationships with projects partners.
- Organize and conduct in person and web based trainings on geospatial data analysis
- Travel and speak as a representative of the National Program Office at professional conferences and outreach events
- Respond to help desk requests regarding geospatial and programming questions
- Directly contributed to 9 feasibility studies covering topics such as; Invasive species, Riparian Ecology, Remote Sensing of Evapotranspiration, and Crop Wild Relatives
- Summary on one project on riparian ecology can be found [here](https://www.youtube.com/watch?v=mI33iQ5Z1qU)

Supervisor: Paul Evangelista, PhD  970-491-2302

Reason for Leaving: Limited term work contract

#### United States Geological Survey; National Geospatial Technical Operations Center
*Geography/GIS Support*

May 2016 to May 2017 | Denver, Colorado

> Ensure that the 100 plus individuals who are producing data and
supporting data production for the [National Map](https://nationalmap.gov/) have the technical support and software to effectively preform their jobs. This position was stationed within the Information Technologies Service section.

- Work directly with GIS users to troubleshoot processing issues
- Ensure all PCs where equipped with required operating software
- Ensure digital systems meet the Standard Operating Procedures

Supervisor: Jennifer Sieverling   303-202-4273 (Jennifer was on extended sick leave when I left and I do not believe she returned to her position.)

Reason for Leaving: Student Internship

#### Colorado Mountain Club: Youth Education Program
*Lead Instructor*

October 2013 to August 2015 | Golden, CO

> Facilitated science and outdoor education programming for school groups (3rd -12th) across the Front Range. This was diverse work which give me great experience in adapting content to match the needs of a specific group.

- Developed and facilitated curriculum
- Ensured the safety of groups in various outdoor settings
- Acted as the point of contact for the organization for school outreach and overnight trips

Supervisor: Holly Barrass 303-996-2751 

Reason for Leaving: Began Graduate Program at University of Colorado Denver

##### Great Sand Dunes National Park and Preserve
*Education Technician*

2 summers(2010,2011) and two 6 month Season (2012, 2013)
| Mosca, CO

> I volunteered for two summers with the Ambassadors for Wilderness(AFW) program. During the 2012 and 2013 seasons I worked as a uniformed ranger managing the AFW program. It was a remarkable opportunity that is very difficult to summarize. If you would like to know about it please watch the [promotional video](https://www.youtube.com/watch?v=fwhb6LhqPU0) I created about the program.

- Organize multiple backcountry trips for middle and high school students from the San Luis Valley
- Develop and facilitate a 3 day instructor training.
- Ensure the program meets the protocols and safety standard of the National Park Service
- Provide interpretive programming for visitors of the Park

Supervisor: Kathy Faz  719-378-6341

Reason for Leaving: End of a grant funded program

#### Adams State Adventure Program
*Trip Leader*

October 2007 to May 2012 | Alamosa, CO

> Performed a variety of duties over my 5 years with the program. These included management of the climbing wall, providing customer service at an equipment rental shop, and facilitating outdoor recreation trips.

- Assistant Instructor on a 14 day college course on Outdoor Leadership
- Organized a "Green Bike Rally" fundraiser fun bike race to help establish the free bike program at Adams State.
-  Acquired over 250 field days over the 5 year period

Supervisor: Mick Daniel  719-522-3910

Reason for Leaving: Student Position

***

# Awards, Recognitions, and Relevant Publications

**Research on Soils and Fluvial Geomorphology in the San Luis Valley**
- Carver, D.P.; Beeton, J.M. Holocene landscape evolution and geoarchaeology of low-order streams in the Rio Grande basin, San Juan Mountains, Colorado, USA. Journal of Quaternary Research 82 (2014), 331-341.

**Riparian Vegetation and Corridor Mapping of the Colorado River Basin**
- Woodward, B.D.; Evangelista, P.H.; Young, N.E.; Vorster, A.G.; West, A.M.; Carroll, S.L.; Girma, R.K.; Hatcher, E.Z.; Anderson, R.; Vahsen, M.L.; Vashisht, A.; Mayer, T.; Carver, D.; Jarnevich, C. CO-RIP: A Riparian Vegetation and Corridor Extent Dataset for Colorado River Basin Streams and Rivers. ISPRS Int. J. Geo-Inf. 2018, 7, 397.

**Regional Award for my Service to the Ambassadors for Wilderness Program**
- 2012 National Park Service Intermountain Region Wilderness Stewardship Award for engaging youth.

**Personal Recipe in a cookbook**
- Wilderness Ranger Cookbook, 2nd: A Collection of Backcountry Recipes by Bureau of Land Management, Forest Service, National Park Service, and U.S. Fish and Wildlife Service Wilderness Rangers.

**Formal training in group facilitation**
- Certificate in Experiential Facilitation; Catalyst Healthy Living February 2014

***

# References

**Kathy Faz**, Chief of Interpretation and Visitor Service, Great Sand Dunes National Park and Preserve   

Office: 719-378-6341 - kathy_faz@nps.gov (Will be effected by Government Shutdown)


**Mick Daniel**, Executive Director of San Luis Valley Great Outdoors

Mobile: 719-522-3910 - mickdaniel@slvgo.com


**Tim Mayer**, Center Lead of the Colorado NASA DEVELOP Node

Mobile: 360-304-8429 - Timothy.Mayer.US@gmail.com
