---
title: <center><span style = 'color:black; font-family:Arial'> Daniel Carver</center></span>
author: <font size = '4'><center> <span style='color:dimgray; font-family:Arial; font-style:normal'>carver.dan1\@gmail.com
  | (630) 612-6557 <br> <a href = "http://carverd.com">carverd.com</a></span></font></center>
output:
  html_document: default
  pdf_document: default
  theme: cayman
---
```{r setup, include=FALSE}
#Set Styles
```




<style>
div.head1 { background-color:#d9d9d9; border-radius: 3px; padding: 5px}
</style>

<style>
div.head2 { background-color:#f0f0f0; border-radius: 1px; padding: 5px;}
</style>


```{css, echo = F}
#left {
  left:-8.33%;
  text-align: left;
  float: left;
  width:48%;
  z-index:-10;
  margin-bottom:-20px;
}

#right {
  left:31.25%;
  top: 75px;
  float: right;
  text-align: left;
  z-index:-10;
  width:50%;
  margin-bottom:-20px;
}

.hangingindent {
  padding-left: 22px ;
  text-indent: -22px ;
}
```

***
<div class = "head1">
<center><font size = '4'><span style='color:black'>**Education**</center></font></span>
</div>

<span style='color:black'><font size = '3'>
University of Colorado Denver
</span><span style='color:dimgray'>
| Graduation Date: May 2017
</font></span><br><span style='color:black'><font size = '2'>
**Masters of Applied Geography and Geospatial Science**
<br>
*Masters Certificate in Geographic Information Science*
<span style='color:dimgray'>
| GPA: 3.86
</font></span></bdi>  


<span style='color:black'><font size = '3'>
Adams State University
</span><span style='color:dimgray'>
| Graduation Date: 05/2012
</font></span><br><span style='color:black'><font size = '2'>
**B.S. Geology & B.A. Physical Geography**
<span style='color:dimgray'>
| GPA: 3.7
</font></span></bdi>  

<hr>


***

<div class = "head1">

<center><font size = '4'><span style='color:black'>**Work Experience**</center></font></span>
</div>


<div class = "head2"><span style='color:black'><font size = '3'>
United States Department of Agriculture; Agricultural Research Service
</span><span style='color:dimgray'>
<br>
| June 2018 to Present
<br>
| Fort Collins, CO
</font></span><br><span style='color:black'><font size = '2'>
**Spatial Scientist**

<span style='color:dimgray'>
| Supervisor: Colin Khoury  970-492-7534
<br>
| Reason for Leaving: 180 day work contract
</font></span></div>

> I collaborate with researchers and curators at the National Laboratory for Genetic Resource Preservation to develop geospatial models that add to the understanding of the distribution, collection, and use of the Crop Wild Relatives.

 - Generate Geospatial models of potential plant locations
 - Produce reports on the relationship between the ARS and BLM's Seeds of Success Program
 - Contribute to the geospatial analysis needs of other USDA researchers

<br>

<div class = "head2"><span style='color:black'><font size = '3'>
NASA DEVELOP
</span><span style='color:dimgray'>
<br>
| June 2017 to September 2018
<br>
| Fort Collins, CO
</font></span><br><span style='color:black'><font size = '2'>
**Geoinformatics Fellow and Assistent Center Lead**

<span style='color:dimgray'>
| Supervisor: Paul Evangelista, PhD  970-491-2302
<br>
| Reason for Leaving: Limited Term Work Contract
</font></span></div>

> Half of my time is spent supporting the node location in Fort Collins and the other half is spent supporting the National Program office in Virginia. At the node level I assisted in administrative task and worked as a member of a research team. At the national level I provided educational trainings and provided geospatial analysis support to all 13 nodes across the country.

- Collaborate with Center lead to maintain day to day operations of 8-10 employees and 6 distinct research projects a year.
- Develop project proposals and maintain relationship with projects partners.  
- Organize and conduct in person and web based trainings on geospatial data analysis
- Travel and speak as a representative of the National Program Office at professional conference and outreach events
- Respond to help desk request regarding geospatial and programming questions  
- Directly contributed to 9 feasibility studys covering topics such as; Invasive species, Riparian Ecology, Remote Sensing of Evapotranspiration, and Crop Wild Relatives
- Summary on one of these projects can be found [here](https://www.youtube.com/watch?v=mI33iQ5Z1qU)

<br>


<div class = "head2"><span style='color:black'><font size = '3'>
United States Geological Survey; National Geospatial Technical Operations Center
</span><span style='color:dimgray'>
<br>
| May 2016 to May 2017
<br>
| Denver, Colorado
</font></span><br><span style='color:black'><font size = '2'>
**Geography/GIS Support**

<span style='color:dimgray'>
| Supervisor: Jennifer Sieverling   303-202-4273 (Jennifer was on extended sick leave when I left and I do not believe she returned to her position.)
<br>
| Reason for Leaving: Student Internship, I left after Graduating
</font></span></div>

> Ensure that the 100 plus individuals who are producing data and
supporting data production for the [National Map](https://nationalmap.gov/) have the technical support and software to effectively preform their jobs. This position was stationed within the Information Technologies Service section.

- Work directly with GIS user to troubleshoot processing issues
- Ensure all PCs where equipped with required operating software
- Ensure digital systems meet the Standard Operating Procedures

<br>

<div class = "head2"><span style='color:black'><font size = '3'>
Colorado Mountain Club: Youth Education Program
</span><span style='color:dimgray'>
<br>
| October 2013 to August 2015
<br>
| Golden, CO
</font></span><br><span style='color:black'><font size = '2'>
**Lead Instructor**

<span style='color:dimgray'>
| Supervisor: Holly Barrass 303-996-2751
<br>
| Reason for Leaving: Started Graduate Program
</font></span></div>

> Facilitated science and outdoor education programming for school groups (3rd -12th) across the Front Range. This was diverse work which give me great experience in adapting content to match the needs of a specific group.

- Developed and facilitated curriculum
- Ensured the safety of groups in various outdoor settings
- Acted as the point of contact for the organization for school outreach and overnight trips

<br>


<div class = "head2"><span style='color:black'><font size = '3'>
Great Sand Dunes National Park and Preserve
</span><span style='color:dimgray'>
<br>
| 2 summers(2010,2011) and two 6 month Season (2012, 2013)
<br>
| Mosca, CO
</font></span><br><span style='color:black'><font size = '2'>
**Education Technician**

<span style='color:dimgray'>
| Supervisor: Kathy Faz  719-378-6341
<br>
| Reason for Leaving: End of a grant funded program
</font></span></div>

> I volunteered for two summers with the Ambassadors for Wilderness Program. During the 2012 and 2013 seasons I worked as a uniformed ranger managing the AFW program. It was an remarkable opportunity that is very difficult to summarize. If you like to know about it please watch the [promotional video](https://www.youtube.com/watch?v=fwhb6LhqPU0) I created about the program.

- Organize multiple backcountry trip for middle and high school student from the San Luis Valley
- Develop and facilitate a 3 day instructor training.
- Ensure the program meets the protocols and safety standard of the National Park Service
- Provide interpretive programming for visitors of the Park

<br>


<div class = "head2"><span style='color:black'><font size = '3'>
Adams State Adventure Program
</span><span style='color:dimgray'>
<br>
| October 2007 to May 2012
<br>
| Alamosa, CO
</font></span><br><span style='color:black'><font size = '2'>
**Trip Leader**

<span style='color:dimgray'>
| Supervisor: Mick Daniel  719-522-3910
<br>
| Reason for Leaving: Student Position, I graduated
</font></span></div>

> Prefromed a variety of duties over my 5 years with the program. These included management of the climbing wall, providing customer service at a equipment rental shop, and facilitating outdoor recreation trips.

- Assistant Instructor on a 14 day college course on Outdoor Leadership
- Organized a "Green Bike Rally" fundraiser fun bike race to help establish the free bike program at Adams State.
-  Acquired over 250 field days over the 5 year period

***
***

<div class = "head1">
<center><font size = '4'><span style='color:black'>**Awards, Recognitions, and relevant Publications**</center></font></span>
</div>

<bdi style="color:black"><div id="left">
**Independent Research on Soils and Geomorphology in the San Luis Valley**
- Holocene landscape evolution and geoarchaeology of low-order streams in the Rio Grande basin, San Juan Mountains, Colorado, USA. Journal of Quaternary Research 82 (2014), 331-341.

**Regional Award for my Service to the Ambassadors for Wilderness Program**
- 2012 National Park Service Intermountain Region Wilderness Stewardship Award for engaging </div>

<div id="right">

**Personal Recipe in a cookbook**
- Wilderness Ranger Cookbook, 2nd: A Collection of Backcountry Recipes by Bureau of Land Management, Forest Service, National Park Service, and U.S. Fish and Wildlife Service Wilderness Rangers.

**Formal training in group facilitation**
- Certificate in Experiential Facilitation; Catalyst Healthy Living February 2014
<br>
<br>
<br>
</bdi></div>

<hr>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class = "head1">
<center><font size = '4'><span style='color:black'>**References**</center></font></span>
</div>

**Kathy Faz**, Cheif of Interpretation and Visitor Service, Great Sand Dunes National Park and Preserve   
Office: 719-378-6341 - kathy_faz@nps.gov

**Mick Daniel**, Executive Director of San Luis Valley Great Outdoors
Mobile: 719-522-3910 - mickdaniel@slvgo.com

**Tim Mayer**, Center Lead of the Colorado NASA DEVELOP Node
Mobile: 360-304-8429 - Timothy.Mayer.US@gmail.com

**Colin Khoury**, Post-Doctoral Research Associate with the Agricultural Research Service
Mobile: 970-237-9571 - C.Khoury@cgiar.org
